export const JOB_ROLES = [
  "Account Manager",
  "Accountant",
  "Accounting",
  "Administrative Assistant",
  "Apprentice Electrician",
  "Apprentice Plumber",
  "Architecture",
  "Assistant Chef",
  "Assistant Manager",
  "Barista",
  "Bartender",
  "Bus Driver",
  "Business Analyst",
  "Business Development",
  "Cashier",
  "Catering Manager",
  "Chef",
  "Childcare Assistant",
  "Childcare Worker",
  "Classroom Assistant",
  "Construction Laborer",
  "Construction Manager",
  "Consulting",
  "Content Writer",
  "Cook",
  "Customer Service",
  "Customer Service Associate",
  "Customer Service Representative",
  "Customer Success Manager",
  "Cyber Security",
  "Data Analyst",
  "Data Engineer",
  "Data Entry Clerk",
  "Data Scientist",
  "Delivery Driver",
  "DevOps Engineer",
  "Digital Marketing Specialist",
  "Dispatcher",
  "Dishwasher",
  "Doorman",
  "Early Years Teacher",
  "Education Assistant",
  "Electrician",
  "Engineering",
  "Event Coordinator",
  "Event Planner",
  "Facilities Manager",
  "Finance",
  "Food and Beverage Manager",
  "Front Desk Agent",
  "Front of House Manager",
  "Graphic Designer",
  "Groundskeeper",
  "Guest Services Agent",
  "Healthcare",
  "Home Health Aide",
  "Hospitality Manager",
  "Housekeeper",
  "Hotel Manager",
  "Human Resources",
  "Instructional Assistant",
  "IT Support",
  "Janitor",
  "Legal",
  "Line Cook",
  "Loader",
  "Machine Learning Engineer",
  "Maintenance Technician",
  "Marketing",
  "Material Handler",
  "Maitre D",
  "Mechanical Engineer",
  "Mental Health Counselor",
  "Mobile Developer",
  "Nanny",
  "Nursing",
  "Occupational Therapist",
  "Office Manager",
  "Operations Analyst",
  "Operations Manager",
  "Order Picker",
  "Painter",
  "Paramedic",
  "Personal Trainer",
  "Pharmacy Technician",
  "Physical Therapist",
  "Physical Therapy Assistant",
  "Preschool Teacher",
  "Product Designer",
  "Product Manager",
  "Project Coordinator",
  "Project Manager",
  "Property Manager",
  "Quality Assurance Engineer",
  "Quantity Surveyor",
  "Receptionist",
  "Recruiter",
  "Registered Nurse",
  "Retail Associate",
  "Retail Manager",
  "Retail Supervisor",
  "Sales",
  "Sales Manager",
  "School Counselor",
  "School Nurse",
  "Security Guard",
  "Security Officer",
  "Server",
  "Shift Supervisor",
  "Social Media Manager",
  "Social Worker",
  "Software Developer",
  "Software Engineer",
  "Speech Therapist",
  "Store Associate",
  "Store Manager",
  "Substitute Teacher",
  "Supply Chain",
  "Teacher Assistant",
  "Teaching",
  "Therapist",
  "Tutor",
  "UX/UI Designer",
  "UX Researcher",
  "Waiter",
  "Waitress",
  "Warehouse Associate",
  "Warehouse Manager",
  "Warehouse Supervisor",
  "Web Developer",
  "Welder",
];
