export const JOB_ROLES = [
  "Account Manager",
  "Accountant",
  "Accounting",
  "Accounts Assistant",
  "Accounts Payable Assistant",
  "Accounts Receivable Assistant",
  "Administrative Assistant",
  "Administrator",
  "Apprentice Electrician",
  "Apprentice Plumber",
  "Architecture",
  "Assistant Accountant",
  "Assistant Chef",
  "Assistant Manager",
  "Barista",
  "Bartender",
  "Bookkeeper",
  "Bus Driver",
  "Business Analyst",
  "Business Development",
  "Care Assistant",
  "Cashier",
  "Catering Manager",
  "Chef",
  "Childcare Assistant",
  "Childcare Worker",
  "Classroom Assistant",
  "Cleaner",
  "Commis Chef",
  "Construction Laborer",
  "Construction Manager",
  "Consulting",
  "Content Writer",
  "Cook",
  "Customer Service",
  "Customer Service Associate",
  "Customer Service Representative",
  "Customer Success Manager",
  "Cyber Security",
  "Data Administrator",
  "Data Analyst",
  "Data Engineer",
  "Data Entry Clerk",
  "Data Scientist",
  "Delivery Driver",
  "Dental Nurse",
  "DevOps Engineer",
  "Digital Marketing Assistant",
  "Digital Marketing Specialist",
  "Dispatcher",
  "Dishwasher",
  "Domestic Assistant",
  "Doorman",
  "Early Years Teacher",
  "Education Assistant",
  "Electrician",
  "Engineering",
  "Event Coordinator",
  "Event Planner",
  "Facilities Manager",
  "Finance",
  "Finance Assistant",
  "Food and Beverage Manager",
  "Front Desk Agent",
  "Front of House Manager",
  "Graduate Trainee",
  "Graphic Designer",
  "Groundskeeper",
  "Guest Services Agent",
  "Healthcare",
  "Healthcare Assistant",
  "Helpdesk Analyst",
  "HGV Driver",
  "Home Health Aide",
  "Hospitality Manager",
  "Hotel Manager",
  "Housekeeper",
  "HR Assistant",
  "Human Resources",
  "Instructional Assistant",
  "IT Support",
  "IT Technician",
  "Janitor",
  "Junior Accountant",
  "Junior Data Analyst",
  "Junior Finance Analyst",
  "Junior Software Developer",
  "Kitchen Assistant",
  "Legal",
  "Legal Assistant",
  "Line Cook",
  "Loader",
  "Machine Learning Engineer",
  "Maintenance Technician",
  "Marketing",
  "Marketing Assistant",
  "Material Handler",
  "Maitre D",
  "Mechanical Engineer",
  "Mental Health Counselor",
  "Mobile Developer",
  "Nanny",
  "Nursery Assistant",
  "Nursing",
  "Occupational Therapist",
  "Office Administrator",
  "Office Manager",
  "Operations Analyst",
  "Operations Manager",
  "Order Picker",
  "Painter",
  "Paralegal",
  "Payroll Assistant",
  "Paramedic",
  "Personal Trainer",
  "Pharmacy Assistant",
  "Pharmacy Technician",
  "Physical Therapist",
  "Physical Therapy Assistant",
  "Picker Packer",
  "Preschool Teacher",
  "Product Designer",
  "Product Manager",
  "Project Coordinator",
  "Project Manager",
  "Property Manager",
  "Quality Assurance Engineer",
  "Quantity Surveyor",
  "Receptionist",
  "Recruiter",
  "Recruitment Consultant",
  "Registered Nurse",
  "Retail Assistant",
  "Retail Associate",
  "Retail Manager",
  "Retail Supervisor",
  "Sales",
  "Sales Assistant",
  "Sales Manager",
  "School Counselor",
  "School Nurse",
  "Security Guard",
  "Security Officer",
  "Server",
  "Shift Supervisor",
  "Social Media Assistant",
  "Social Media Manager",
  "Social Worker",
  "Software Developer",
  "Software Engineer",
  "Speech Therapist",
  "Store Associate",
  "Store Manager",
  "Substitute Teacher",
  "Supervisor",
  "Supply Chain",
  "Teacher Assistant",
  "Teaching",
  "Teaching Assistant",
  "Team Leader",
  "Therapist",
  "Trainee Accountant",
  "Trainee Teacher",
  "Tutor",
  "UX Researcher",
  "UX/UI Designer",
  "Van Driver",
  "Waiter",
  "Waitress",
  "Warehouse Associate",
  "Warehouse Manager",
  "Warehouse Operative",
  "Warehouse Supervisor",
  "Web Designer",
  "Web Developer",
  "Welder",
];
